### ISSUE TITLE
Keep consistency with included stories when writing MDX manually

### ISSUE THREAD

**Issue by iuscare** [wingsuit-designsystem/wingsuit#104]
**Is your feature request related to a problem? Please describe.**
We are able to write our own MDX documentaiton, which is very powerful. You've even included custom documentation tokens, which makes writing documentation less painful. Now it would only be convenient, if the layout of a story stays the same, when including it into a manual created MDX file by using `<PatternPreview>`. Up to now the `<sbdocs sbdocs-preview>`wrapper with its viewport or border lines around the story gets eliminated.

**Describe the solution you'd like**
Sometimes it is useful to add additional documentation texts like you do in your grid component. So either it would be useful to add the ability to add markup within the .yml file of the pattern itself or to render imported stories with `<PatternPreview>`the same as automatic created stories. 

**Additional context**
Desired Solution for every documentation - currently only automatic MDX:
<img width="1324" alt="Bildschirmfoto 2020-12-04 um 04 05 56" src="https://user-images.githubusercontent.com/33871309/101116839-2980f700-35e6-11eb-8c0e-bf6a804a17be.png">

Current implementation for MDX created manually:
<img width="1317" alt="Bildschirmfoto 2020-12-04 um 04 06 10" src="https://user-images.githubusercontent.com/33871309/101116871-356cb900-35e6-11eb-830d-4a8ae1e226f6.png">

**Comment by christianwiedemann** [comment]
Hi, yes I also had the wish to add markup to the yml to document my stuff. The problem right now is that a storybook component renders the description. I need to check if I can simple replace that. Will let you know.

**Comment by christianwiedemann** [comment]
Now markup is supported in automatic pattern generation. If you want to have the same look and feel in your mdx docs you need an <Preview> Wrapper

```
import { Meta, Title, Subtitle, Preview } from '@storybook/addon-docs/blocks';
<Preview withToolbar={true}>
  <PatternPreview variant={pattern.getDefaultVariant()} columns="4" config="equal"/>
</Preview>

```

**Comment by iuscare** [comment]
You simply rock! Thanks!
