### ISSUE TITLE
Allow custom path to icons for spritemaps

### ISSUE THREAD

**Issue by iuscare** [wingsuit-designsystem/wingsuit#111]
**Is your feature request related to a problem? Please describe.**
In the [storybook preset](https://github.com/wingsuit-designsystem/wingsuit/blob/00e93da8c47a711fa1774517be4a89ba0e093125/packages/core/src/server/presets/storybook.ts) a specific path to the icons for spritemap generation is expected, which follows the atomic design methodology. Currently the generation of the svgs.json fails, if there is no atoms path defined within the namespace.

**Describe the solution you'd like**
It would be handy, if we can modify this part in case, we do not want to follow the methodology

**Describe alternatives you've considered**
Up to now I can avoid the interruption by defining an additional atom path within the namespace, but this feels a little bit of hacky. It looks like this:
```
/**
 * Global namespaces
 */

const path = require('path');

const patterns = path.resolve(__dirname, 'patterns');

module.exports = {
  tokens: path.resolve(__dirname, 'tokens'),
  clientside: path.resolve(__dirname, 'clientside'),
  protons: path.resolve(patterns, '00-misc'),
  macros: path.resolve(patterns, '01-macros'),
  embeds: path.resolve(patterns, '02-embeds'),
  atoms: path.resolve(patterns, '03-components'),
  components: path.resolve(patterns, '03-components'),
  pages: path.resolve(patterns, '04-layouts'),
};
```

**Comment by christianwiedemann** [comment]
Hi Pascal, 

I know that issue and we also had this problem with the workaround "atomic" namespace. The problem with the svg path is that we need to solve two issues before:

1. How to configure presets. Internal and external presets.
2. How to handle svg spritemaps more generic. Right now we can only handle one spritemap which is not enough from my point of view. It often make sense to group images in several spritemap. (For example a spritemap with country flags)

So my Ideas to 1. 
A preset has method defaultConfig which returns the defaultConfig. :) In your wingsuit.config.js you have a parameters entry where you can overwrite this. (A bit storybook is don't that with addons)
So the wingsuit.config.js would look like:
```
...
parameters: {
   svg: {svgSourceFolder: 'path'}
}
...
For multiple spritemaps I will open another issue later.

**Comment by iuscare** [comment]
That would be awesome. The file is the most sensible place for such configuration parameters

**Comment by christianwiedemann** [comment]
I update the svg preset. I also updated the svg preset https://wingsuit-designsystem.github.io/assets/svg/

**Comment by christianwiedemann** [comment]
Will close this for now. If you have any issues let me know.
