### ISSUE TITLE
HTML storybook addon

### ISSUE THREAD

**Issue by mhlozek** [wingsuit-designsystem/wingsuit#120]
Hi, I would like to use HTML storybook addon to display rendered HTML code of twig template.

I tried to install addon with npm and then add addon to main.js file, but I ended with some errors in console (Can't resolve 'jquery'...?)

Could you try to add this addon to your system?

Thanks a lot!

**Comment by christianwiedemann** [comment]
You mean this one https://github.com/whitespace-se/storybook-addon-html

**Comment by christianwiedemann** [comment]
Hm works for me. I added it to the tailwind starter-kit

![settings](https://user-images.githubusercontent.com/393489/108536322-a1ed7f00-72dc-11eb-8ce4-20a931abd44b.png)

Can you give me more info about your setup.

**Comment by mhlozek** [comment]
Yes, that is the addon I mean and I use bootstrap starter kit.

I just found that jquery was missing in node_modules, so I add it to dev dependencies and it works now 💪
