### ISSUE TITLE
Drupal locale exception

### ISSUE THREAD

**Issue by woldtwerk** [wingsuit-designsystem/wingsuit#121]
**Describe the bug**
The drupale locale module tries to parse js files from the ws stream wrapper. It checks for ":" in the filepath and throws an exception. 
web/core/modules/locale/locale.module:1108
In my case it was alpine.js, possibly all the other js files as well.

**To Reproduce**
activate drupal locale module
refresh page in FE theme

**Expected behavior**
works

**Comment by christianwiedemann** [comment]
@woldtwerk Yes we know the problem. it is a drupal bug with Stream wrappers.

Here is the Ticket:
https://www.drupal.org/project/drupal/issues/2735717

We are not sure if this lands in drupal core. If you want to be save change the path in the libraries.

**Comment by woldtwerk** [comment]
thx for the info.
Patch 28 is working nicely.
