### ISSUE TITLE
Glidejs slider does not display the first slide

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#126]
**Describe the bug**
Even when testing with storybook you can see 1 less slide 

if you remove the `{% if key != "region_label" %}` condition all the slides display correctly

what is this condition for ?

**Comment by christianwiedemann** [comment]
@GiorgosK We used the pattern as a section in layout builder and looping through all blocks. The first block is the label. We want to skip this. The question is why is not working in storybook. That is strange. Will check that.

**Comment by christianwiedemann** [comment]
@GiorgosK Works for me now. Will close this issue. Please reopen it if you have still this issue. Thanks for reporting!
