### ISSUE TITLE
Change source/default path to source/myproject

### ISSUE THREAD

**Issue by mhlozek** [wingsuit-designsystem/wingsuit#129]
Hi there,
is it possible to change path source/default to something like source/nameofmyproject ?
I tried it but get errors Can't resolve 'wsdesignsystem/namespaces' and Can't resolve 'wspatterns'

**Comment by christianwiedemann** [comment]
Hi,

you can set the path to the designsystem in your wingsuit.config.js

Checkout the [config stub](https://github.com/wingsuit-designsystem/wingsuit/blob/master/packages/core/src/stubs/defaultWingsuitConfig.stub.ts).

**Comment by mhlozek** [comment]
Thank you for your reply, I checked config stub and it works.

And just one question (or should I create new issue?):

How could I change theme logo (or the whole storybook theme)?
I tried it in manager.js, but it has no effect. Could you give me some example/snippet please?

**Comment by mhlozek** [comment]
Just set custom theme in preview.js, but why it doesn't work in manager.js?

**Comment by christianwiedemann** [comment]
This should work.
```

// .storybook/manager.js

import { addons } from '@storybook/addons';
import { themes } from '@storybook/theming';

themes.dark.brandImage = 'images/logo.svg';
addons.setConfig({
  theme: themes.dark,
});

```

**Comment by mhlozek** [comment]
Great. Thank you very much!
