### ISSUE TITLE
ERR! Error: Cannot find module 'tailwindcss/plugin'

### ISSUE THREAD

**Issue by danleecpi** [wingsuit-designsystem/wingsuit#130]
**Describe the bug**
After installing from scratch I get the following error when running storybook.

`ERR! Error: Cannot find module 'tailwindcss/plugin'`

**To Reproduce**
1. npx @wingsuit-designsystem/cli init
2. npm install
3. npm run dev:storybook

**Expected behavior**
Storybook runs

**Versions**
macOS Big Sur 11.0.1
Node Version: 11.15.0

**Screenshots**
<img width="1287" alt="Screenshot 2021-03-26 at 14 24 15" src="https://user-images.githubusercontent.com/59832142/112654844-bb3b9b00-8e47-11eb-852b-3e2a161cace9.png">

**Comment by christianwiedemann** [comment]
Hi, can you give me more details. Which OS? Which node version. And I can't open your screenshot.

Thanks!

**Comment by danleecpi** [comment]
@christianwiedemann Updated original message above. Thanks!

**Comment by christianwiedemann** [comment]
That is a problem of tailwindcss/forms I think 

See https://github.com/tailwindlabs/tailwindcss-forms/issues/31

Can you try to delete node_modules and try it with yarn. For me it is hard to reproduce.

**Comment by danleecpi** [comment]
Ok so I do...

yarn install
yarn dev:storybook

and get...

/bin/sh: start-storybook: command not found
error Command failed with exit code 127.

**Comment by christianwiedemann** [comment]
Ah you need node version > 12 for tailwindcss 2. That is probably the reason. Would be great if you check that.

**Comment by danleecpi** [comment]
Thanks @christianwiedemann - I did the following and it worked. I should have checked!

`nvm use --lts`

_Now using node v14.16.0 (npm v6.14.11)_

```
yarn install
yarn dev:storybook
```

I'm actually going to try and use this in a Craft CMS project as it uses twig. Is there anything I need to be aware of do you think? Obviously this was built for Drupal.

**Comment by christianwiedemann** [comment]
I know from the slack group that other developers using CraftCMS. Maybe you join the slack group and ask there. But in general it should not be a problem.

**Comment by iuscare** [comment]
@danleecpi I am using wingsuit and CraftCMS, too. So far now problems at all. I develop & maintain, document the twig components in storybook and port them over to craftcms afterwards. So I am using two separate instances. One is wingsuit and one is the classic CraftCMS approach.
