### ISSUE TITLE
Typography Docs not rendering Typeface

### ISSUE THREAD

**Issue by danleecpi** [wingsuit-designsystem/wingsuit#137]
**Describe the bug**
I noticed in the typography docs page that the fonts are not loaded after install.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install wingsuit and run storybook
2. Browse to Typography Docs and you will see the error. The screenshot below shows my own typeface which I have added... this wasn't working with Poppins font either on a fresh install.

Font rendering in components is working without issue.

<img width="1639" alt="Screenshot 2021-04-04 at 09 58 00" src="https://user-images.githubusercontent.com/59832142/113504523-95418500-9530-11eb-89b1-3595ab1e3b6a.png">

**Comment by christianwiedemann** [comment]
Hi! The typography is an mdx file. You can find it under apps/storybook/00-base/typeset.stories.mdx. 

You can fix this by changing line 25 from 

`<Typeset fontFamily={key} classNamePrefix="text-" fontSizes={fontSizes} />`
to

`<Typeset fontFamily={fontFamilies[key][0]} classNamePrefix="text-" fontSizes={fontSizes} />`

I fixed it in the startkit.

Thanks for reporting!

**Comment by danleecpi** [comment]
Thanks for the fix @christianwiedemann!
