### ISSUE TITLE
Generating New Component using Wizard - Empty Options for App

### ISSUE THREAD

**Issue by danleecpi** [wingsuit-designsystem/wingsuit#138]
**Describe the bug**
Generating a new component does not work. Returns empty options at the first question.

**To Reproduce**
Steps to reproduce the behaviour:
1. cd wingsuit
2. wingsuit yarn ws generate-component
3. Empty options on the first question

**Expected behavior**
Options for the app after the question "Which app should be used? (Use arrow keys)"

**Screenshots**
<img width="1295" alt="Screenshot 2021-04-09 at 11 48 33" src="https://user-images.githubusercontent.com/59832142/114170080-5180be00-992a-11eb-86d9-3915ffeb66ed.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version. Wingsuit 1.0

**Comment by iuscare** [comment]
This seems to be cli version related. Switching back the CLI verison to `1.0.0-rc.6` lets the error disappear and storybook be an option to be selected

**Comment by christianwiedemann** [comment]
Fixed it in 1.0.2.

**Comment by christianwiedemann** [comment]
Run yarn upgrade
