### ISSUE TITLE
ws generate drupal app missing

### ISSUE THREAD

**Issue by woldtwerk** [wingsuit-designsystem/wingsuit#141]
**Describe the bug**
After upgrade to version 1.0.3 ws generate-component only shows storybook as app. I can't select drupal as app

**Expected behavior**
show storybook and drupal in app list

**Screenshots**
![image](https://user-images.githubusercontent.com/32794633/117009227-ceb20f80-aceb-11eb-93d3-1a8dd154df4e.png)

**Desktop (please complete the following information):**
 - OS: mac

**Comment by christianwiedemann** [comment]
What is your use case? 
Is the drupal app using a different source/patterns folder? 

The CLI allows generating presenter templates. And these presenter templates should placed under apps/storybook. For this reason, I disallow all other app types. So it is the expected behavior.

**Comment by woldtwerk** [comment]
well it works. 
But I think I did:
```
Which app should be used? drupal
What type of component would you like to create? Wingsuit component (UI Pattern)
```
for my drupal patterns and

```
Which app should be used? storybook
What type of component would you like to create? Presentation template
```
for may storybook only stuff.
