### ISSUE TITLE
SwiperJS is not actually used in a slider

### ISSUE THREAD

**Issue by miloskroulik** [wingsuit-designsystem/wingsuit#153]
In `slider.wingsuit.yml` I can see this description:

> Javascript slider with swipperjs (https://swiperjs.com/)...

But https://github.com/search?q=org%3Awingsuit-designsystem+swiperjs&type=code shows that this library isn't actually used. I will try to update it to Splide slider when I have a bit of time.

**Comment by christianwiedemann** [comment]
Thanks for reporting. I changed the comment.
