### ISSUE TITLE
Bootstrap starter PostCSS8 issue

### ISSUE THREAD

**Issue by markatli** [wingsuit-designsystem/wingsuit#173]
Getting this warning when upgrading to PostCSS8 for the Bootstrap starter:

postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

Might be helpful if the Bootstrap starter gets the same PostCSS8 upgrade as the Tailwind starter

Thanks!

**Comment by christianwiedemann** [comment]
Hi will change this in 1.1.

**Comment by christianwiedemann** [comment]
Hi I released 1.1 yesterday. The upgraded the bootstrap starter to bootstrap 5 and I am using PostCSS8 now.
