### ISSUE TITLE
Getting Error while init

### ISSUE THREAD

**Issue by Ninellin** [wingsuit-designsystem/wingsuit#174]
When I try to Setup Wingsuit with the "npx @wingsuit-designsystem/cli init" command I get dependency errors (Screenshot).

OS: Ubuntu 20.10
NPM: 7.19.1
Node: v16.5.0

![image](https://user-images.githubusercontent.com/25079254/125918087-693b4043-f0dd-40cd-91c9-a7d6c66c69f7.png)

**Comment by christianwiedemann** [comment]
That is propably a problem with yarn. Can you Upgrade? Or try --branch= master
