### ISSUE TITLE
Webpack - drupal, postcss and wingsuit (support request)

### ISSUE THREAD

**Issue by jowan** [wingsuit-designsystem/wingsuit#180]
New to webpack, so bare with me.

I have customised (putting it kindly) the following files:

```/wingsuit.config.js ```
added a new rules/module for webfonts file-loader

```/node_modules/@wingsuit-designsystem/core/dist/server/presets/drupal.js```
a few customisations, dropped the CSS file support and changed the vendor folder location

```/node_modules/@wingsuit-designsystem/preset-scss/dist/index.js```
a few customisations, made a fixed entry for main.scss and then dynamic support for x.styles.scss

The two second hacks are within ```function webpack(appConfig) {```
and I *think* the first one is the _allowed_ webpack overrides method (?).

Question : can I migrate these changes in to a single place ?
At the moment I'm using a patch, which is fine, but I would like to know how to do this properly for maintainability.
The customizations are about exporting to Drupal.

Thanks for your help

**Comment by christianwiedemann** [comment]
Hi, you could easily create your own preset. You need an own app type. In this app type you can load your configure your presets.

Here the pages preset as example:

https://github.com/wingsuit-designsystem/wingsuit/blob/next/presets/pages/src/index.ts
