### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by woldtwerk** [wingsuit-designsystem/wingsuit#200]
Hi Christian,
was just checking out the latest updates and found the docs not working.
I cloned the repo and used the tailwind starter.

**Describe the bug**
open Storybook in dev or build mode. You'll get an error in console and the story is not loading in the docs container. The story works fine in the canvas tab.

**To Reproduce**
open Storybook in dev or build mode. 
open any story in docs tab.

**Expected behavior**
story renders properly in docs tab

**Screenshots**
![image](https://user-images.githubusercontent.com/32794633/155486450-75d6b9ab-b025-4cef-a85d-19c951bb38f4.png)

![image](https://user-images.githubusercontent.com/32794633/155487128-ce8fe5fd-e957-4800-b6f1-51be43a57c95.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome, brave
 - Version 98

**Additional context**
btw twigdrupal is invite only isn't it?

**Comment by christianwiedemann** [comment]
Hi, did you run npx @wingsuit-designsystem/cli init -k tailwind. It works for me hmm.

**Comment by woldtwerk** [comment]
no I cloned this repo. build the pattern-react package, because there was a dependency to it.
And then went to tailwind starter-kit and tried both dev:storybook and the one which builds it in docs mode.

**Comment by woldtwerk** [comment]
no I cloned this repo. build the pattern-react package, because there was a dependency to it.
And then went to tailwind starter-kit and tried both dev:storybook and the one which builds it in docs mode.

**Comment by woldtwerk** [comment]
no I cloned this repo. build the pattern-react package, because there was a dependency to it.
And then went to tailwind starter-kit and tried both dev:storybook and the one which builds it in docs mode.

**Comment by woldtwerk** [comment]
I just created the tailwind starter via the cli. That worked fine. Not sure what went wrong when with the cloning approach.

**Comment by christianwiedemann** [comment]
Have you run yarn bootstrap in the root
