### ISSUE TITLE
Preset [SCSS]: node-sass v5 dependency throws post install error with Node v16

### ISSUE THREAD

**Issue by avrilpearl** [wingsuit-designsystem/wingsuit#206]
**Describe the bug**
We are using pnpm to manage a monorepo, using Node v16.14.0. On pnpm install, it seems that node-sass v5 throws a post install error. Is it possible to upgrade this dependency for the preset scss library to v6 or higher to enable us to use this preset with node v16.

**Comment by christianwiedemann** [comment]
Hi, I switched to:

"sass": "^1.50.0"

Let me know if it works for you.

**Comment by christianwiedemann** [comment]
run yarn upgrade

**Comment by avrilpearl** [comment]
Thank you @christianwiedemann!
