### ISSUE TITLE
Demo site is no longer working

### ISSUE THREAD

**Issue by ElFredo311** [wingsuit-designsystem/wingsuit#216]
**Describe the bug**
When I visit http://demo.wingsuit.dev.key-tec.de/user/login the drupal install fails by saying "The directory /var/www/files-private does not exist. An automated attempt to create this directory failed,"

**To Reproduce**
1. Go to '.http://demo.wingsuit.dev.key-tec.de/user/login'
2. Select English and click on 'save and continue '
3. See error "The directory /var/www/files-private does not exist. An automated attempt to create this directory failed,"

**Expected behavior**
Drupal installs with the module working

**Comment by christianwiedemann** [comment]
Thanks for reporting. Works again.
