### ISSUE TITLE
template not found

### ISSUE THREAD

**Issue by jphat** [wingsuit-designsystem/wingsuit#217]
**Describe the bug**
I'm having trouble getting Drupal to register components following the Quickstart guide. I did confirm the `dist path` in WS settings, and that `app-drupal` was generated correctly. In particular, 'wingsuit/dist/app-drupal/atomic/patterns/04-templates/site-container.twig' exists.

**To Reproduce**
1. install ws using Quickstart guide: npx @wingsuit-designsystem/cli init -k tailwind
2. enable wingsuit
3. go to /
4. `Twig\Error\LoaderError: Template "@templates/site-container.twig" is not defined in "themes/custom/wingsuit/apps/drupal/templates/layout/page.html.twig" at line 54. in Twig\Loader\ChainLoader->getCacheKey() (line 98 of vendor/twig/twig/src/Loader/ChainLoader.php).`

**Expected behavior**
WS/Drupal to register and use templates and components

**Desktop (please complete the following information):**
 - Node 18.9.0; Yarn 1.22.9;
 - Drupal 9.4.8
 - UI Patterns 8.x-1.3
 - WS companion module 8.x-2.0-beta9
 - Components (3.0.0-beta3)

**Additional context**
Components! v3 have a new format of including components and following that, I have
`
components:
    namespaces:
      foo:
        - ../../dist/app-drupal/atomic/patterns/01-atoms
        - ../../dist/app-drupal/atomic/patterns/02-molecules
        - ../../dist/app-drupal/atomic/patterns/03-organisms
        - ../../dist/app-drupal/atomic/patterns/04-templates
`
and updating 'wingsuit/apps/drupal/templates/layout/page.html.twig' to 
`
{% embed "@foo/site-container.twig" with {
  primary_menu: page.primary_menu,
  language_select: page.language_switcher,
  footer_menu: page.footer_menu,
  highlighted: page.highlighted
} %}
`
changes the error to `Twig\Error\LoaderError: Template "@organisms/header/header.twig" is not defined in "@drupal/site-container.twig" at line 4. in Twig\Loader\ChainLoader->getCacheKey() (line 98 of vendor/twig/twig/src/Loader/ChainLoader.php). `

thanks.

**Comment by jphat** [comment]
I checked the demo site and compared Components module version and looks like the v3 is the culprit. I downgraded to v2 (ui_patterns downgraded to 1.2, matching the demo site) and seems to work but now ran into `Drupal\Component\Plugin\Exception\PluginNotFoundException: The "container" plugin does not exist. Valid plugin IDs for Drupal\ui_patterns\UiPatternsManager are: in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).`

**Comment by finnlewis** [comment]
@jphat did you resolved that last issue? 

I also now see 

`The "container" plugin does not exist`

after downgrading components to

**Comment by jphat** [comment]
@finnlewis, yes I did.

- Component module is locked at version 8.x-2.4
- Wingsuit component module is version 8.x-2.1
- UI Patterns is version 8.x-1.5
- Wingsuit companion dist path: themes/custom/wingsuit/dist/app-drupal

Generate both wingsuit and importantly Drupal files. Clear cache.
