### ISSUE TITLE
Documentation website broken

### ISSUE THREAD

**Issue by blackbart420** [wingsuit-designsystem/wingsuit#219]
Hello mate,
I wanted to show your wonderful project to my boss but the website is broken: https://wingsuit-designsystem.github.io/

Did it move to another website?
Thank you

**Comment by christianwiedemann** [comment]
sure it works for me

**Comment by blackbart420** [comment]
Oh ok weird, it doesn't open properly on Brave, but it's ok on Chrome so no worries :)
