### ISSUE TITLE
menu's menuIsOpen and show/hide

### ISSUE THREAD

**Issue by jphat** [wingsuit-designsystem/wingsuit#236]
**Describe the bug**
changing `menuIsOpen` to anything else like `jamIsOpen` in `header.twig` and `hamburger.twig` seem to break its functionality. is there anywhere else where the show/hide is controlled that I am missing>

**To Reproduce**
1. Go to `wingsuit/source/default/patterns/03-organisms/header` and `wingsuit/source/default/patterns/01-atoms/hamburger`
2. Change all occurrences of `menuIsOpen` to something else and save
3. See error

**Expected behavior**
since the truthiness and show/hide seems to be controlled by click and classes, would expect any name to work

**Comment by iuscare** [comment]
Hi @jphat, if you are running into this while using drupal, please also see the variable in the html.html.twig and adapt it

https://github.com/wingsuit-designsystem/wingsuit/blob/4e98f96ba78664b591c0f1cafd6e12879a91fa55/starter-kits/tailwind/apps/drupal/templates/layout/html.html.twig#L36
