### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by christianwiedemann** [wingsuit-designsystem/wingsuit#4]
We need a logo.

**Comment by Eloanea** [comment]
Hello, what kind of logo do you need ?

**Comment by christianwiedemann** [comment]
Hi @Eloanea ,

great that you like to contribute. We would need an Svg file. 
Maybe a very reduced "wingsuit flyer" in the style of [tailwind logo](https://tailwindcss.com/). Maybe we could use one wave of the tailwind logo on the bottom of the flyer. 
If you have other ideas go for it.

**Comment by Eloanea** [comment]
Hi @christianwiedemann,
 Sorry for my translation message. Yes, with pleasure to help you, the flyer is for a special event? And for the colors do you want to keep the same as the waves?
I can draw you a little "model" to give you an idea if you want.
Eloane

**Comment by christianwiedemann** [comment]
@Eloanea,
great! And yes we the wave should be cloud. 
About the color: Not 100% sure if we should use the same color? I think it would look good but maybe it is to near on tailwind.  What do you think?

**Comment by Eloanea** [comment]
@christianwiedemann 
Well we can change the color for have a blue more deeper like the sky or something more a lighter color (blue/grey) like a cloud in the sky.
So at the end of the afternoon i will make some propositions for you and like that it will help you 
for have a clear idea of ​​the things to do and touch up. I'll send you there tonight or maximum at the morning, tomorrow ! :)

**Comment by Eloanea** [comment]
@christianwiedemann 
Hello, I made 3 designs with different colors. 
I hope I understood your request and don't hesitate to give me a return about colors and forms ! 
(i have same logo with a black background too)
Eloanea
![logochristian1](https://user-images.githubusercontent.com/60181867/74207162-bb49fd00-4c7e-11ea-8f11-59f093e49aa3.png)
![logochristian2](https://user-images.githubusercontent.com/60181867/74207175-c4d36500-4c7e-11ea-820a-20b3a03d494a.png)
![logochristian3](https://user-images.githubusercontent.com/60181867/74207178-c735bf00-4c7e-11ea-80ad-07ac5e8d3f6a.png)

**Comment by christianwiedemann** [comment]
Hi Elona,

many thanks for your great work! I like the first one because it is more abstract. The style is quit cool but the perspective is not perfect. He looks like he jumps somewhere down.

I attached an wingsuit flyer where I think the perspective is better. 
![photo_2020-02-11_15-19-19](https://user-images.githubusercontent.com/393489/74247110-dc920400-4ce5-11ea-99b7-7b5562f2274d.jpg)

Some of my thoughts:
- More abstract is better. (Maybe even more than the first one)
- Maybe we set the flyer in a circle?
- I like the colors of the 3. flyer of your first work (blue/grey) - or we use simple the tailwind colors to have more tailwind?

Whant do you think? 

Thanks again a lot for great work so far!

**Comment by Eloanea** [comment]
@christianwiedemann 
Hello,
Well yes i will do that. For the if you like this one, we will keep it. 
I will work on it, and send to you a new design Thursday or Friday.

I have a question about the logo, what is its story? is it for an event or something else?

Your welcome, i'm training in infography and i help in the same occasion !
Eloanea :)

**Comment by Eloanea** [comment]
Hello, my week was busy sorry, i will work on it this week
Eloane

**Comment by christianwiedemann** [comment]
Hi Eloanea,

My week was also quit busy. To your questions. It is not a event it is a open source project. A Drupal theme (suit) for the tailwind css framework. Have you seen the readme? https://github.com/wingsuit-designsystem/wingsuit. 

So it is an opensource project so no rush. Is is ready when it is ready :). And thanks again for your support!

**Comment by Eloanea** [comment]
@christianwiedemann Hi thanks for your message ! I wil send you somthing tonigh !

**Comment by Eloanea** [comment]
@christianwiedemann  Hello again, i've make one design with some proposition with differents colors ! Like that you can see the colors witn a white and black background.
I waiting for your observations, thanks for for your patience !
Eloane
![logotest3-wingsuit](https://user-images.githubusercontent.com/60181867/75678774-a6192a80-5c8e-11ea-9329-1b8f74164163.png)
