### ISSUE TITLE
When using the `yarn ws generate-component` behaviour file should not be referenced with .js at the end

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#47]
running `yarn ws generate-component` create reference in `index.js` such as this 

```bash
import './_status.behavior.js';
``` 

and the storybook watcher/builder complains with 

```
  5:8  error  Unexpected use of file extension "js" for "./_status.behavior.js"  import/extensions

✖ 1 problem (1 error, 0 warnings)
```

deleting the `.js` part makes the problem go away but perhaps the component generator should be corrected to not include the file ending

**Comment by christianwiedemann** [comment]
this is already fixed in beta10.

**Comment by GiorgosK** [comment]
I did `yarn upgrade` and it updated some packages 
should I be doing anything else ?

**Comment by christianwiedemann** [comment]
@GiorgosK Please reopen if you have problems.
