### ISSUE TITLE
twig raw filter ignored within storybook, but works when used within drupal

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#48]
**Describe the bug**
twig raw not considered within storybook, but works when used within drupal

**To Reproduce**
Create any component that includes html 
`text: "<strong>strong text</strong> and regular text"`
display using raw filter
`{{ text | raw }}

**Expected behavior**
Strong should be interpretted as HTML tag but it is not

**Screenshots**
![twig raw](https://user-images.githubusercontent.com/520704/93689168-9c450080-fad4-11ea-9fa6-7658df7e9e16.png)

**Comment by christianwiedemann** [comment]
Knob escaping variables by default. I disabled this behavior. Should work now.

**Comment by christianwiedemann** [comment]
in beta11
