### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by christianwiedemann** [wingsuit-designsystem/wingsuit#71]
**Describe the bug**

- [x] Move tailblocks text to the component
- [x] Add description
- [x] Remove field

**Comment by iuscare** [comment]
Wingsuit is awesome! The ability to override the wingsuit theme would be nice. Up to now creating an own theme.ts and using it within the manager.js only works on initial page load. Navigating between pages will show the wingsuit brand again, or am I missing something/is it intended that way?

**Comment by christianwiedemann** [comment]
@iuscare yes you are right. Currently it is hardcoded. I will move that out to make it easier for others to set there own theme.

**Comment by christianwiedemann** [comment]
and great that you like it!

**Comment by christianwiedemann** [comment]
@iuscare In beta17 the theme is not hardcoded anymore.
