### ISSUE TITLE
Make or at least document how svg icons can be more versatile

### ISSUE THREAD

**Issue by GiorgosK** [wingsuit-designsystem/wingsuit#76]
**Is your feature request related to a problem? Please describe.**
svg icons have the power to be colored using the fill attribute (or perhaps the stroke attribute)
some of the icons included in the example patterns are not recollorable as can be seen in the screenshot

![versatile_icons](https://user-images.githubusercontent.com/520704/98784481-dad7a700-2403-11eb-8c51-6fd751ec194e.png)

**Describe the solution you'd like**
It is most times simple enough to just strip the fill attribute from within svg and this allows it to be colored using outside css rules.  It would be nice to try to include only svg icons that are recolorable (perhaps the same icons can just be modified) or other svg icons can be included.

Would you consider adjusting the included icons to be able to be changed with fill attribute ? 
Would you accept replacing the icons that are not able to be changed with fill attribute ? (even after modifications)
what is your source of choosing svg icons (if there is one)

If the above is accepted perhaps the svg icon pattern can be modified to allow settings or fields for changing the color.

**Comment by christianwiedemann** [comment]
yes good idea. To be honest I did not really think about the icons. I just copy them from tailwind demo pages. We should clean them (remove stroke and fill) up and we should add setting to give them a color.

**Comment by GiorgosK** [comment]
This should be closed than
