### ISSUE TITLE
Use storybook 6.1

### ISSUE THREAD

**Issue by iuscare** [wingsuit-designsystem/wingsuit#81]
**Is your feature request related to a problem? Please describe.**
The request is not related to a problem. Storybook 6.1 is the first in a series of performance-oriented Storybook releases and includes a new and more flexible sidebar, manager caching for faster startup, asynchronous loaders, react 17 support and single story hosting just to mention a few improvements. It might be worth to update. I already tried this on your `beta.21` with `npx sb@next upgrade` in the wingsuit and sotrybook folder and haven't run into issues with a quick test and overview. Maybe there is room for improvements for your custom loader to leverage the new caching mechanism for better startup times, but at least an update does not seem to break wingsuit directly. Just a consideration. :-)

All the best!

**Comment by christianwiedemann** [comment]
Hi Pascal, 

yes the 6.1 is a very good release and it does not break anything. You can just delete the yarn.lock and run yarn install to upgrade.

**Comment by iuscare** [comment]
Ah, yeah you´re right. Minor version jump. Thanks! :-)
